### ISSUE TITLE
No option for playing MKV files or Chromecast

### ISSUE THREAD

**Issue by arindammitra06** [dj-yacine-flutter/player_js#1]
Thanks for the package. I wanted to use this plugin to play mkv files on web but I cant find an option for so. Also how to add a cast button?

**Comment by djeddi-yacine** [comment]
> Thanks for the package. I wanted to use this plugin to play mkv files on web but I cant find an option for so. Also how to add a cast button?

You are welcome. To play the mkv video just put the URL of it Also to make cast button you need to create it in the player website  or choose a player that already has the cast function this is the link : [https://playerjs.com](PlayerJS)  . If you need help feel free to ask 🙏

**Comment by arindammitra06** [comment]
Thanks for the quick reply. But I couldnt find any template player which has cast button. Can you show me which player it is? A screenshot should do maybe. 

Also can you try playing this mkv file? This one has video but no audio.
https://beta.sastatv.com/Hindi/Pathaan%20(2023)%20HD.mkv

**Comment by djeddi-yacine** [comment]
> Thanks for the quick reply. But I couldnt find any template player which has cast button. Can you show me which player it is? A screenshot should do maybe. 
> 
> Also can you try playing this mkv file? This one has video but no audio.
> https://beta.sastatv.com/Hindi/Pathaan%20(2023)%20HD.mkv
> 

The Chromecast is a pro feature for pro members but I found just one for free in this URL you will get it  : []()https://playerjs.com/skins/t=video&tmp=6bu8dvme5mle he look like ![Screenshot_2023-04-08-03-55-14-047-edit_com.android.chrome.jpg](https://user-images.githubusercontent.com/127781608/230700309-3b369361-0a00-49ca-baa0-b46e5c5d7b1c.jpg)

**Comment by arindammitra06** [comment]
I tested the MKV file, but sorry playerjs isnt playing audio on the files. Also the player you mentioned is a paid one and doesn't support chromecast. Thanks by the way.
